local MiniTest = require("mini.test")
local H = require("tests.helpers")

local child = H.new_child()
local T = H.set(child)

local policy = vim.fs.joinpath(H.workspace, "oncall", "routing.sigil")
local main = vim.fs.joinpath(H.deps, "nvim-treesitter")
local master = vim.fs.joinpath(H.deps, "nvim-treesitter-master")

-- A sigil parser built outside the tests, e.g. by CI, as a .so path.
local parser = vim.env.SIGIL_TEST_PARSER

local function with_rtp(dir)
  child.lua("vim.opt.rtp:prepend(...)", { dir })
end

local function pin()
  return child.lua_get("require('sigil.config').grammar_revision")
end

local sigil = "https://github.com/SpechtLabs/sigil"
local grammar = "editors/tree-sitter-sigil"

-- want.revision = true stands for the pinned revision, which only the child
-- knows.
T["install_info()"] = MiniTest.new_set({
  parametrize = {
    {
      "the defaults",
      {},
      { url = sigil, location = grammar, revision = true, queries = grammar .. "/queries" },
    },
    {
      "a revision",
      { revision = "v0.9.0" },
      { url = sigil, location = grammar, revision = "v0.9.0", queries = grammar .. "/queries" },
    },
    {
      "a fork",
      { url = "https://github.com/me/sigil", location = "grammar" },
      { url = "https://github.com/me/sigil", location = "grammar", revision = true, queries = "grammar/queries" },
    },
    {
      "a local checkout",
      { path = "~/src/sigil/editors/tree-sitter-sigil" },
      { path = "~/src/sigil/editors/tree-sitter-sigil", queries = "queries" },
    },
  },
})
T["install_info()"]["for main from"] = function(_, opts, want)
  if want.revision == true then
    want.revision = pin()
  end
  local got = child.lua(
    [[
    local options = require("sigil.config").set({ treesitter = ... })
    return require("sigil.treesitter").install_info(options.treesitter)
  ]],
    { opts }
  )
  H.eq(got, want)
end

T["master_install_info()"] = MiniTest.new_set({
  parametrize = {
    {
      "the defaults",
      {},
      {
        url = "https://github.com/SpechtLabs/sigil",
        location = "editors/tree-sitter-sigil",
        files = { "src/parser.c" },
        requires_generate_from_grammar = false,
      },
    },
    {
      "a local checkout",
      { path = "/src/sigil/editors/tree-sitter-sigil" },
      {
        url = "/src/sigil/editors/tree-sitter-sigil",
        files = { "src/parser.c" },
        requires_generate_from_grammar = false,
      },
    },
  },
})
T["master_install_info()"]["from"] = function(_, opts, want)
  local got = child.lua(
    [[
    local options = require("sigil.config").set({ treesitter = ... })
    return require("sigil.treesitter").master_install_info(options.treesitter)
  ]],
    { opts }
  )
  if not opts.path then
    want.revision = pin()
  end
  H.eq(got, want)
end

T["the shipped queries say they're generated from the pin"] = function()
  local header = ("; Code generated by scripts/sync-grammar.lua from SpechtLabs/sigil@%s. DO NOT EDIT."):format(pin())
  local files = vim.fn.globpath(vim.fs.joinpath(H.root, "queries", "sigil"), "*.scm", false, true)
  H.neq(#files, 0)
  for _, file in ipairs(files) do
    H.eq({ vim.fs.basename(file), vim.fn.readfile(file, "", 1)[1] }, { vim.fs.basename(file), header })
  end
end

T["flavor()"] = MiniTest.new_set({
  parametrize = {
    { "without nvim-treesitter", false, vim.NIL },
    { "main", main, "main" },
    { "master", master, "master" },
  },
})
T["flavor()"]["detects"] = function(_, dir, want)
  if dir then
    with_rtp(dir)
  end
  H.eq(child.lua_get("require('sigil.treesitter').flavor(true)"), want)
end

T["flavor() doesn't load nvim-treesitter by itself"] = function()
  with_rtp(main)
  H.eq(child.lua_get("require('sigil.treesitter').flavor()"), vim.NIL)
  H.eq(child.lua_get("package.loaded['nvim-treesitter.parsers'] == nil"), true)
end

T["nvim-treesitter main"] = MiniTest.new_set()

T["nvim-treesitter main"]["lists sigil after TSUpdate"] = function()
  with_rtp(main)
  H.eq(child.lua_get("vim.tbl_contains(require('nvim-treesitter.config').get_available(), 'sigil')"), true)
  H.eq(
    child.lua_get("require('nvim-treesitter.parsers').sigil.install_info"),
    child.lua_get("require('sigil.treesitter').install_info()")
  )
end

T["nvim-treesitter main"]["keeps sigil when it reloads its table"] = function()
  with_rtp(main)
  child.lua([[
    require("nvim-treesitter.config").get_available()
    package.loaded["nvim-treesitter.parsers"] = nil
    require("nvim-treesitter.config").get_available()
  ]])
  H.eq(child.lua_get("require('nvim-treesitter.parsers').sigil ~= nil"), true)
end

T["nvim-treesitter main"]["gets the configured revision"] = function()
  with_rtp(main)
  child.lua([[require("sigil").setup({ treesitter = { revision = "0123abc" } })]])
  child.lua([[require("nvim-treesitter.config").get_available()]])
  H.eq(child.lua_get("require('nvim-treesitter.parsers').sigil.install_info.revision"), "0123abc")
end

T["nvim-treesitter main"]["doesn't list sigil with treesitter.enabled = false"] = function()
  with_rtp(main)
  child.lua([[require("sigil").setup({ treesitter = { enabled = false } })]])
  H.eq(child.lua_get("vim.tbl_contains(require('nvim-treesitter.config').get_available(), 'sigil')"), false)
end

T["nvim-treesitter master gets sigil in the first sigil buffer"] = function()
  with_rtp(master)
  child.cmd("edit " .. policy)
  local conf = child.lua_get("require('nvim-treesitter.parsers').get_parser_configs().sigil")
  H.eq(conf.filetype, "sigil")
  H.eq(conf.install_info, child.lua_get("require('sigil.treesitter').master_install_info()"))
end

T["without a parser"] = MiniTest.new_set()

T["without a parser"]["keeps the regex highlighting"] = function()
  child.cmd("edit " .. policy)
  H.eq(child.lua_get("require('sigil.treesitter').has_parser()"), false)
  H.eq(child.lua_get("vim.treesitter.highlighter.active[vim.api.nvim_get_current_buf()] == nil"), true)
  H.eq(child.b.current_syntax, "sigil")
end

-- A stand-in for nvim-treesitter main that records install() calls, and a
-- tree-sitter CLI on $PATH when cli is true.
local function stub_install(opts, cli)
  local bin = vim.fn.tempname()
  vim.fn.mkdir(bin, "p")
  if cli then
    vim.fn.writefile({ "#!/bin/sh", "exit 0" }, vim.fs.joinpath(bin, "tree-sitter"))
    vim.fn.setfperm(vim.fs.joinpath(bin, "tree-sitter"), "rwxr-xr-x")
  end
  child.boot(nil, bin)
  child.lua(
    [[
    _G.installs = {}
    package.loaded["nvim-treesitter.parsers"] = {}
    package.loaded["nvim-treesitter"] = {
      install = function(langs)
        table.insert(_G.installs, langs)
        return { await = function(_, cb) cb() end }
      end,
    }
    require("sigil").setup(...)
  ]],
    { opts }
  )
  child.cmd("edit " .. policy)
  child.cmd("edit " .. vim.fs.joinpath(H.workspace, "alert_routing.sigil"))
  return child.lua_get("_G.installs")
end

T["without a parser"]["installs it once with ensure_installed"] = function()
  H.eq(stub_install({}, true), { { "sigil" } })
end

T["without a parser"]["doesn't install without the tree-sitter CLI"] = function()
  H.eq(stub_install({}, false), {})
end

T["without a parser"]["doesn't install with ensure_installed = false"] = function()
  H.eq(stub_install({ treesitter = { ensure_installed = false } }, true), {})
end

-- Skips the case unless SIGIL_TEST_PARSER names a parser, and loads it.
local function need_parser()
  if not parser or vim.fn.filereadable(parser) == 0 then
    MiniTest.skip("set SIGIL_TEST_PARSER to a built sigil parser")
  end
  child.lua("vim.treesitter.language.add('sigil', { path = ... })", { parser })
end

T["with a parser"] = MiniTest.new_set()

T["with a parser"]["highlights with tree-sitter"] = function()
  need_parser()
  child.cmd("edit " .. policy)
  H.eq(child.lua_get("vim.treesitter.highlighter.active[vim.api.nvim_get_current_buf()] ~= nil"), true)
end

T["with a parser"]["captures"] = MiniTest.new_set({
  parametrize = {
    { "when", 3, 1, "keyword.conditional" },
    { "a field", 3, 12, "variable.member" },
    { "a comment", 1, 1, "comment" },
    { "a policy name", 2, 8, "module" },
  },
})
T["with a parser"]["captures"]["highlight"] = function(_, row, col, capture)
  need_parser()
  child.cmd("enew | set filetype=sigil")
  child.api.nvim_buf_set_lines(0, 0, -1, true, {
    "// Routes critical alerts.",
    "policy oncall.routing: AlertRouting@1",
    "when alert.severity == critical {",
    "}",
  })
  local captures = child.lua(
    "return vim.tbl_map(function(c) return c.capture end, vim.treesitter.get_captures_at_pos(0, ...))",
    { row - 1, col - 1 }
  )
  H.eq({ capture, vim.tbl_contains(captures, capture) }, { capture, true })
end

T["with a parser"]["folds with fold = true"] = function()
  need_parser()
  child.lua([[require("sigil").setup({ treesitter = { fold = true } })]])
  child.cmd("edit " .. policy)
  if child.lua_get("require('sigil.treesitter').has_query('folds')") then
    H.eq(child.wo.foldexpr, "v:lua.vim.treesitter.foldexpr()")
  end
end

T["with a parser"]["parses every query"] = function()
  need_parser()
  local queries = vim.fn.globpath(vim.fs.joinpath(H.root, "queries", "sigil"), "*.scm", false, true)
  H.neq(#queries, 0)
  for _, file in ipairs(queries) do
    local name = vim.fn.fnamemodify(file, ":t:r")
    local ok, err = child.lua("return pcall(vim.treesitter.query.get, 'sigil', ...)", { name })
    H.eq({ name, ok and "parses" or err }, { name, "parses" })
  end
end

T["installs the parser in the first sigil buffer"] = function()
  if vim.env.SIGIL_TEST_INSTALL ~= "1" then
    MiniTest.skip("set SIGIL_TEST_INSTALL=1 to build the parser from the pinned revision")
  end
  child.boot(nil, vim.fn.fnamemodify(vim.fn.exepath("tree-sitter"), ":h"))
  with_rtp(main)
  -- Its own install directory, so the parser doesn't outlive the case. It has
  -- to exist before it joins 'runtimepath', as stdpath("data")/site does.
  local dir = vim.fn.tempname()
  vim.fn.mkdir(dir, "p")
  child.lua("require('nvim-treesitter').setup({ install_dir = ... })", { dir })
  -- What a user with nvim-treesitter main sees: open a file, wait for the
  -- build, get tree-sitter highlighting and indentation.
  child.cmd("edit " .. policy)
  H.eq(H.wait(child, "vim.treesitter.highlighter.active[vim.api.nvim_get_current_buf()] ~= nil", 300000), true)
  H.eq(child.bo.indentexpr, "v:lua.require'nvim-treesitter'.indentexpr()")
end

return T
